create table student(id int,name varchar(15) not null,gender varchar(6),phoneno varchar(10) unique,age int, check(age>=18),primary key(id));
insert into student values(13,"Siva","male","9994532266",18);
insert into student values(4,"Starr","male","9952496151",100);
insert into student values(1,"king","male","9444437999",21);
insert into student values(2,"sivant","male","7373738590",31);
select * from student;
alter table student add mark int;
update student set mark=90 where mark=NULL;
create table course(cid int primary key,ctitle varchar(15),credit int,fid int,foreign key(fid)references student(id));
insert into course values(11,"AI",3,1);
insert into course values(12,"CS",4,2);
insert into course values(13,"AI",3,13);
insert into course values(14,"CS",4,4);
alter table student drop column mark;
select * from student;
select * from course;
describe course;
select * from student order by(age);
select * from student order by(age) desc;
select * from student order by id;
select name from student where age=18;
select * from student where age between 20 and 40;
create table stu1(id int,name varchar(15) not null,gender varchar(6),phoneno varchar(10) unique,age int, check(age>=18),dob date,primary key(id,dob));
create table cr1(cid int primary key,ctitle varchar(15),credit int,fid int,fdob date,foreign key(fid,fdob)references stu1(id,dob));
select * from student group by age desc;
select max(id) from student;
select * from student where age=(select min(age) from student);