(self.AMP=self.AMP||[]).push({n:"amp-form",v:"1911070201440",f:(function(AMP,_){
var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={a:!0},ea={};try{ea.__proto__=da;ca=ea.a;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function n(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ua=b.prototype};function ha(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function ia(a){return new Promise(function(b){b(a())})}function ja(){var a,b,c;this.ta=new Promise(function(a,d){b=a;c=d});this.Ja=b;this.Ha=c;this.ga=0;if(a)for(var d=0;d<a.length;d++)this.add(a[d])}ja.prototype.add=function(a){var b=this,c=++this.ga;Promise.resolve(a).then(function(a){b.ga===c&&b.Ja(a)},function(a){b.ga===c&&b.Ha(a)});return this.ta};
ja.prototype.then=function(a,b){return this.ta.then(a,b)};function ka(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var la=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ma(a){var b=Object.create(null);if(!a)return b;for(var c;c=la.exec(a);){var d=ka(c[1],c[1]),e=c[2]?ka(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var na=Object.prototype.toString;function oa(a){return a?Array.prototype.slice.call(a):[]};var p=self.AMP_CONFIG||{},pa={thirdParty:p.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:p.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof p.thirdPartyFrameRegex?new RegExp(p.thirdPartyFrameRegex):p.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:p.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof p.cdnProxyRegex?new RegExp(p.cdnProxyRegex):p.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:p.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:p.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/]};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var q=self.__AMP_LOG;function r(){if(!q.user)throw Error("failed to call initLogConstructor");return q.user}function t(){if(q.dev)return q.dev;throw Error("failed to call initLogConstructor");}function u(a,b,c,d){r().assert(a,b,c,d,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};var qa=Object.prototype.hasOwnProperty;function v(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function w(a){return a||{}}
function ra(a,b){var c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.G=b.t;a.B=b.s;a.V=b.d;if(d.includes(a.B))throw Error("Source object has a circular reference.");d.push(a.B);a.G!==a.B&&(a.V>c?Object.assign(a.G,a.B):Object.keys(a.B).forEach(function(a){return function(b){var c=a.B[b];if(qa.call(a.G,b)){var d=a.G[b];if("[object Object]"===na.call(c)&&"[object Object]"===na.call(d)){e.push({t:d,s:c,d:a.V+1});return}}a.G[b]=c}}(a)));a={B:a.B,G:a.G,V:a.V}}}
;function x(){var a=100;this.Da=a;this.fa=this.ma=0;this.Y=Object.create(null)}x.prototype.has=function(a){return!!this.Y[a]};x.prototype.get=function(a){var b=this.Y[a];if(b)return b.access=++this.fa,b.payload};x.prototype.put=function(a,b){this.has(a)||this.ma++;this.Y[a]={payload:b,access:this.fa};if(!(this.ma<=this.Da)){t().warn("lru-cache","Trimming LRU cache");a=this.Y;var c=this.fa+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.ma--)}};function sa(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var ta=w({c:!0,v:!0,a:!0,ad:!0,action:!0}),ua,va,wa=/[?&]amp_js[^&]*/,xa=/[?&]amp_gsa[^&]*/,ya=/[?&]amp_r[^&]*/,za=/[?&]amp_kit[^&]*/,Aa=/[?&]usqp[^&]*/;
function y(a){var b;ua||(ua=self.document.createElement("a"),va=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new x));var c=b?null:va,d=ua;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;
e.origin=d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a}function Ba(a,b,c){if(!b)return a;var d=a.split("#",2),e=d[0].split("?",2),f=e[0]+(e[1]?c?"?"+b+"&"+e[1]:"?"+e[1]+"&"+b:"?"+b);return f+=d[1]?"#"+d[1]:""}
function Ca(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(Array.isArray(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")};function Da(a,b){if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=
e.getAttribute("content").split(",");for(var f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0)}Object.assign(c,Ea(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(d=a.AMP_CONFIG["allow-url-opt-in"],a=ma(a.location.originalHash||a.location.hash),e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}var g=c;return!!g[b]}
function Ea(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){t().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};var Fa={},A=(Fa["ampdoc-fie"]={isTrafficEligible:function(){return!0},branches:[["21065001"],["21065002"]]},Fa);function B(a,b){var c=a.ownerDocument.defaultView,d=c.__AMP_TOP||(c.__AMP_TOP=c),e=c!=d;var f=d;if(Da(f,"ampdoc-fie")){f.__AMP_EXPERIMENT_BRANCHES=f.__AMP_EXPERIMENT_BRANCHES||{};for(var g in A)if(qa.call(A,g)&&!qa.call(f.__AMP_EXPERIMENT_BRANCHES,g))if(A[g].isTrafficEligible&&A[g].isTrafficEligible(f)){if(!f.__AMP_EXPERIMENT_BRANCHES[g]&&Da(f,g)){var h=A[g].branches;f.__AMP_EXPERIMENT_BRANCHES[g]=h[Math.floor(Math.random()*h.length)]||null}}else f.__AMP_EXPERIMENT_BRANCHES[g]=null;f="21065002"===
(f.__AMP_EXPERIMENT_BRANCHES?f.__AMP_EXPERIMENT_BRANCHES["ampdoc-fie"]:null)}else f=!1;var k=f;e&&!k?b=Ga(c,b)?C(c,b):null:(a=D(a),a=E(a),b=Ga(a,b)?C(a,b):null);return b}function F(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return C(a,b)}function G(a,b){var c=D(a);c=E(c);return C(c,b)}function Ha(a,b){return Ia(E(a),b)}function D(a){return a.nodeType?F((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function E(a){a=D(a);return a.isSingleDoc()?a.win:a}
function C(a,b){Ga(a,b);var c=Ja(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Ka(a,b){var c=Ia(a,b);if(c)return c;a=Ja(a);a[b]=La();return a[b].promise}function Ia(a,b){var c=Ja(a)[b];if(c){if(c.promise)return c.promise;C(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Ja(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}
function Ga(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}function La(){var a=new ha,b=a,c=b.promise,d=b.resolve;b=b.reject;c.catch(function(){});return{obj:null,promise:c,resolve:d,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var Ma=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function Na(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};var Oa;function Pa(a,b){for(var c=[],d=a.parentElement;d;d=d.parentElement)b(d)&&c.push(d);return c}function Qa(a){var b="fieldset";/^[\w-]+$/.test(b);b=b.toUpperCase();return Pa(a,function(a){return a.tagName==b})}function H(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)};function Ra(a,b,c){var d=Ha(a,b);if(d)return d;var e=D(a);return e.waitForBodyOpen().then(function(){var a=e.win;var b=e.win.document.head;if(b){var d={};b=b.querySelectorAll("script[custom-element],script[custom-template]");for(var k=0;k<b.length;k++){var m=b[k];m=m.getAttribute("custom-element")||m.getAttribute("custom-template");d[m]=!0}d=Object.keys(d)}else d=[];a=d.includes(c)?F(a,"extensions").waitForExtension(a,c):Promise.resolve();return a}).then(function(){var d=e.win;return d.__AMP_EXTENDED_ELEMENTS&&
d.__AMP_EXTENDED_ELEMENTS[c]?Ka(E(a),b):null})};function I(a){return G(a,"resources")};var J,Sa="Webkit webkit Moz moz ms O o".split(" ");function Ta(a,b,c){var d;var e=a.style;if(!sa(b,"--")){J||(J=v());var f=J[b];if(!f){f=b;if(void 0===e[b]){var g=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var h=0;h<Sa.length;h++){var k=Sa[h]+g;if(void 0!==e[k]){g=k;break b}}g=""}void 0!==e[g]&&(f=g)}J[b]=f}b=f}b&&(a.style[b]=d?c+d:c)}function Ua(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};var K;function Va(a,b,c){var d=void 0,e=a,f=c;var g=function(a){try{return f(a)}catch(z){throw self.__AMP_REPORT_ERROR(z),z;}};var h=Wa(),k=!1;d&&(k=d.capture);e.addEventListener(b,g,h?d:k);return function(){e&&e.removeEventListener(b,g,h?d:k);g=e=f=null}}function Wa(){if(void 0!==K)return K;K=!1;try{var a={get capture(){K=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return K};function Xa(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a}function Ya(a,b,c){return Va(a,b,c)}function Za(a,b){var c=b,d=Va(a,"mouseup",function(a){try{c(a)}finally{c=null,d()}});return d}function $a(a){var b,c,d=new Promise(function(b){c=Za(a,b)});d.then(c,c);b&&b(c);return d};function ab(a,b){function c(c){g=null;f=a.setTimeout(d,e);b.apply(null,c)}function d(){f=0;g&&c(g)}var e=100,f=0,g=null;return function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];f?g=b:c(b)}};function cb(a){var b=a.getRootNode();this.Ea=b.ownerDocument||b;this.j=this.Ea.defaultView;this.oa=G(a,"viewport");this.R=[];this.R.push(Ya(b,"input",function(a){a=a.target;"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&db(a)}));this.R.push(Ya(b,"mousedown",function(a){1==a.which&&(a=a.target,"TEXTAREA"==a.tagName&&eb(a))}));var c=b.querySelectorAll("textarea");this.R.push(Ya(b,"amp:dom-update",function(){c=b.querySelectorAll("textarea")}));var d=ab(this.j,function(a){a.relayoutAll&&fb(c)});
this.R.push(this.oa.onResize(d));gb(c)}function hb(a){function b(){var b=c.querySelector("textarea[autoexpand]");b&&!d?d=new cb(a):!b&&d&&(d.dispose(),d=null)}var c=a.getRootNode(),d=null;Va(c,"amp:dom-update",b);b()}cb.prototype.dispose=function(){this.R.forEach(function(a){return a()})};
function gb(a){Promise.all(oa(a).map(function(a){return ib(a).then(function(b){b&&(r().warn("AMP-FORM",'"textarea[autoexpand]" with initially scrolling content will not autoexpand.\nSee https://github.com/ampproject/amphtml/issues/20839'),a.removeAttribute("autoexpand"))})}))}function ib(a){var b=I(a);return b.measureElement(function(){return a.scrollHeight>a.clientHeight})}function fb(a){H(a,function(a){"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&db(a)})}
function eb(a){var b=I(a);Promise.all([b.measureElement(function(){return a.scrollHeight}),$a(a)]).then(function(c){var d=c[0],e=0;return b.measureMutateElement(a,function(){e=a.scrollHeight},function(){d!=e&&a.removeAttribute("autoexpand")})})}
function db(a){var b=I(a),c=a.ownerDocument.defaultView,d=0,e=0,f=0,g=jb(a);b.measureMutateElement(a,function(){var b=c.getComputedStyle(a)||v();e=a.scrollHeight;var k=parseInt(b.getPropertyValue("max-height"),10);f=isNaN(k)?Infinity:k;d="content-box"==b.getPropertyValue("box-sizing")?-parseInt(b.getPropertyValue("padding-top"),10)+-parseInt(b.getPropertyValue("padding-bottom"),10):parseInt(b.getPropertyValue("border-top-width"),10)+parseInt(b.getPropertyValue("border-bottom-width"),10)},function(){return g.then(function(b){a.classList.toggle("i-amphtml-textarea-max",
b+d>f);var c="iAmphtmlHasExpanded"in a.dataset,g=c||e<=b;g&&(a.dataset.iAmphtmlHasExpanded="",Ta(a,"height",b+d+"px"))})})}
function jb(a){var b=a.ownerDocument,c=b.defaultView,d=b.body,e=I(a),f=a.cloneNode(!1);f.classList.add("i-amphtml-textarea-clone");var g=0,h=0,k=!1;return e.measureMutateElement(d,function(){var b=c.getComputedStyle(a)||v(),d=parseInt(b.getPropertyValue("max-height"),10);g=parseInt(b.getPropertyValue("width"),10);k=isNaN(d)||a.scrollHeight<d},function(){k&&(a.scrollTop=0);Ta(f,"width",g+"px");b.body.appendChild(f)}).then(function(){return e.measureMutateElement(d,function(){h=f.scrollHeight},function(){var a=
f;a.parentElement&&a.parentElement.removeChild(a)})}).then(function(){return h})};function L(a){for(var b=a.elements,c={},d=/^(?:input|select|textarea)$/i,e=/^(?:submit|button|image|file|reset)$/i,f=/^(?:checkbox|radio)$/i,g={},h=0;h<b.length;g={F:g.F},h++){var k=b[h],m=k,z=m.checked;g.F=m.name;var bc=m.multiple,cc=m.options,dc=m.tagName,bb=m.type;m=m.value;!g.F||kb(k)||!d.test(dc)||e.test(bb)||f.test(bb)&&!z||(void 0===c[g.F]&&(c[g.F]=[]),bc?H(cc,function(a){return function(b){b.selected&&c[a.F].push(b.value)}}(g)):c[g.F].push(m))}var Q=lb(a);Q&&Q.name&&(a=Q.name,void 0===c[a]&&
(c[a]=[]),c[Q.name].push(Q.value));Object.keys(c).forEach(function(a){0==c[a].length&&delete c[a]});return c}function lb(a){var b=a.elements,c=b.length,d=a.ownerDocument.activeElement,e=null;for(a=0;a<c;a++){var f=b[a],g=f.type;if("BUTTON"==f.tagName||"submit"==g)if(e||(e=f),d==f)return d}return e}function kb(a){if(a.disabled)return!0;a=Qa(a);for(var b=0;b<a.length;b++)if(a[b].disabled)return!0;return!1}
function mb(a){switch(a.type){case "select-multiple":case "select-one":a=a.options;for(var b=0;b<a.length;b++)if(a[b].selected!==a[b].defaultSelected)return!1;break;case "checkbox":case "radio":return a.checked===a.defaultChecked;default:return a.value===a.defaultValue}return!0};function nb(a,b){return a.hasAttribute("verify-xhr")?new ob(a,b):new pb(a)}function M(a){this.h=a}M.prototype.onCommit=function(){qb(this);a:{var a=this.h.elements;for(var b=0;b<a.length;b++){var c=a[b];if(!c.disabled&&!mb(c)){a=!0;break a}}a=!1}return a?this.xa():Promise.resolve({updatedElements:[],errors:[]})};M.prototype.xa=function(){return Promise.resolve({updatedElements:[],errors:[]})};function qb(a){(a=a.h.elements)&&H(a,function(a){a.setCustomValidity("")})}
function pb(){M.apply(this,arguments)}n(pb,M);function ob(a,b){this.h=a;this.$=b;this.U=null;this.sa=[]}n(ob,M);ob.prototype.xa=function(){var a=this,b=this.$().then(function(){return[]},function(a){return rb(a)});return sb(this,b).then(function(b){return tb(a,b)})};function sb(a,b){if(!a.U){a.U=new ja;var c=function(){return a.U=null};a.U.then(c,c)}return a.U.add(b)}
function tb(a,b){function c(a){return b.every(function(b){return a.name!==b.name})}var d=[],e=a.sa;a.sa=b;for(var f=0;f<b.length;f++){var g=b[f],h=r().assertString(g.name,"Verification errors must have a name property");g=r().assertString(g.message,"Verification errors must have a message property");h=r().assertElement(a.h.querySelector('[name="'+h+'"]'),"Verification error name property must match a field name");h.checkValidity()&&(h.setCustomValidity(g),d.push(h))}var k=e.filter(c).map(function(b){return a.h.querySelector('[name="'+
b.name+'"]')});return{updatedElements:d.concat(k),errors:b}}function rb(a){return(a=a.response)?a.json().then(function(a){return a.verifyErrors||[]},function(){return[]}):Promise.resolve([])};function ub(a,b){var c=F(a,"platform");return c.isIos()&&11==c.getMajorVersion()?new vb(b):FormData.prototype.entries&&FormData.prototype.delete?new N(b):new O(b)}function O(a){this.C=a?L(a):v()}O.prototype.append=function(a,b){var c=String(a);this.C[c]=this.C[c]||[];this.C[c].push(String(b))};O.prototype.delete=function(a){delete this.C[a]};
O.prototype.entries=function(){var a=this,b=[];Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.push([c,a])})});var c=0;return{next:function(){return c<b.length?{value:b[c++],done:!1}:{value:void 0,done:!0}}}};O.prototype.getFormData=function(){var a=this,b=new FormData;Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.append(c,a)})});return b};function N(a){this.D=new FormData(a);a&&(a=lb(a))&&a.name&&this.append(a.name,a.value)}
N.prototype.append=function(a,b){this.D.append(a,b)};N.prototype.delete=function(a){this.D.delete(a)};N.prototype.entries=function(){return this.D.entries()};N.prototype.getFormData=function(){return this.D};function vb(a){N.call(this,a);var b=this;a&&H(a.elements,function(a){"file"==a.type&&0==a.files.length&&(b.D.delete(a.name),b.D.append(a.name,new Blob([]),""))})}n(vb,N);
vb.prototype.append=function(a,b,c){b&&"object"==typeof b&&""==b.name&&0==b.size?this.D.append(a,new Blob([]),c||""):this.D.append(a,b)};var wb={INPUT:!0,SELECT:!0,TEXTAREA:!0};function xb(a,b){this.h=a;this.j=b;this.O=0;this.K=v();this.na=null;this.za=this.ba=!1;this.la();for(a=0;a<this.h.elements.length;++a)yb(this,this.h.elements[a]);P(this)}l=xb.prototype;l.onSubmitting=function(){this.ba=!0;P(this)};l.onSubmitError=function(){this.ba=!1;P(this)};l.onSubmitSuccess=function(){this.ba=!1;this.na=ub(this.j,this.h).getFormData();this.K=v();this.O=0;P(this)};
function P(a){var b=0<a.O&&!a.ba;if(b!==a.za){a.h.classList.toggle("amp-form-dirty",b);var c=Xa(a.j,"amp:form-dirtiness-change",w({isDirty:b}),{bubbles:!0});a.h.dispatchEvent(c)}a.za=b}l.la=function(){this.h.addEventListener("input",this.ra.bind(this));this.h.addEventListener("reset",this.Ga.bind(this));this.h.addEventListener("amp:form-value-change",this.ra.bind(this))};l.ra=function(a){yb(this,a.target);P(this)};l.Ga=function(){this.K=v();this.O=0;P(this)};
function yb(a,b){var c=b.hidden;if(wb[b.tagName]&&b.name&&!c&&!kb(b)){a:switch(b.tagName){case "INPUT":c="checkbox"==b.type||"radio"==b.type?!b.checked:!b.value;break a;case "TEXTAREA":c=!b.value;break a;case "SELECT":c=!1;break a;default:throw Error("isFieldEmpty: "+b.tagName+" is not a supported field element.");}(c=c||mb(b))||(a.na?(c=b.value,c=a.na.get(b.name)===c):c=!1);c?(b=b.name,a.K[b]&&(a.K[b]=!1,--a.O)):(b=b.name,a.K[b]||(a.K[b]=!0,++a.O))}};function zb(){this.o=null}l=zb.prototype;l.add=function(a){var b=this;this.o||(this.o=[]);this.o.push(a);return function(){b.remove(a)}};l.remove=function(a){this.o&&(a=this.o.indexOf(a),-1<a&&this.o.splice(a,1))};l.removeAll=function(){this.o&&(this.o.length=0)};l.fire=function(a){if(this.o)for(var b=this.o,c=0;c<b.length;c++)(0,b[c])(a)};l.getHandlerCount=function(){return this.o?this.o.length:0};function Ab(){this.qa=new zb}Ab.prototype.beforeSubmit=function(a){return this.qa.add(a)};Ab.prototype.fire=function(a){this.qa.fire(a)};var Bb=["GET","POST"];function Cb(a){var b=a.getAttribute("crossorigin");return b&&"amp-viewer-auth-token-via-post"===b.trim()?Ra(a,"amp-viewer-assistance","amp-viewer-assistance").then(function(a){u(a,'crossorigin="amp-viewer-auth-token-post" requires amp-viewer-assistance extension.');return a.getIdTokenPromise()}).then(function(a){return a||""}).catch(function(){return""}):Promise.resolve(void 0)};function Db(a,b){var c="amp-form";this.T=a;this.A=b;this.Ka=c}Db.prototype.isSupported=function(){var a=this.T.getAmpDoc();return a.isSingleDoc()&&a.getRootNode().documentElement.hasAttribute("allow-viewer-render-template")?this.T.hasCapability("viewerRenderTemplate"):!1};Db.prototype.ssr=function(a,b,c,d){c=void 0===c?null:c;d=void 0===d?{}:d;var e;c||(e=this.A.maybeFindTemplate(a));return this.T.sendMessageAwaitResponse("viewerRenderTemplate",Eb(this,b,e,c,d))};
Db.prototype.applySsrOrCsrTemplate=function(a,b){if(this.isSupported()){u("string"===typeof b.html,"Server side html response must be defined");var c=this.A.findAndSetHtmlForTemplate(a,b.html)}else c=Array.isArray(b)?this.A.findAndRenderTemplateArray(a,b):this.A.findAndRenderTemplate(a,b);return c};
function Eb(a,b,c,d,e){e=void 0===e?{}:e;var f=w({type:a.Ka}),g="successTemplate",h=d&&d[g]?d[g]:c;h&&(f[g]={type:"amp-mustache",payload:h.innerHTML});var k="errorTemplate",m=d&&d[k]?d[k]:null;m&&(f[k]={type:"amp-mustache",payload:m.innerHTML});e&&Object.assign(f,e);a=b.xhrUrl;c=b.fetchOpt;b=Object.assign({},c);if((d=c.body)&&"function"==typeof d.getFormData){c=c.body;b.headers["Content-Type"]="multipart/form-data;charset=utf-8";c=c.entries();d=[];for(e=c.next();!e.done;e=c.next())d.push(e.value);
b.body=d}return w({originalRequest:{input:a,init:b},ampComponent:f})};function Fb(a,b){this.ka=b;this.oa=G(a,"viewport");this.ya=F(a.win,"vsync");this.ia=null;this.ha="";this.ca=!1;this.J=a.win.document.createElement("div");Ua(this.J,!1);this.J.classList.add("i-amphtml-validation-bubble");this.J.__BUBBLE_OBJ=this;a.getBody().appendChild(this.J)}Fb.prototype.isActiveOn=function(a){return this.ca&&a==this.ia};Fb.prototype.hide=function(){this.ca&&(this.ca=!1,this.ia=null,this.ha="",this.ya.run({measure:void 0,mutate:Gb},{bubbleElement:this.J}))};
Fb.prototype.show=function(a,b){if(!this.isActiveOn(a)||b!=this.ha){this.ca=!0;this.ia=a;this.ha=b;var c={message:b,targetElement:a,bubbleElement:this.J,viewport:this.oa,id:this.ka};this.ya.run({measure:Hb,mutate:Ib},c)}};function Gb(a){a.bubbleElement.removeAttribute("aria-alert");a.bubbleElement.removeAttribute("role");for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);Ua(a.bubbleElement,!1)}function Hb(a){a.targetRect=a.viewport.getLayoutRect(a.targetElement)}
function Ib(a){for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);var c=a.bubbleElement.ownerDocument.createElement("div");c.id="bubble-message-"+a.id;c.textContent=a.message;a.bubbleElement.setAttribute("aria-labeledby",c.id);a.bubbleElement.setAttribute("role","alert");a.bubbleElement.setAttribute("aria-live","assertive");a.bubbleElement.appendChild(c);Ua(a.bubbleElement,!0);b=a.bubbleElement;a={top:a.targetRect.top-10+"px",left:a.targetRect.left+a.targetRect.width/2+"px"};for(var d in a)Ta(b,
d,a[d])};var Jb,Kb,Lb=0;function R(a){this.form=a;this.ampdoc=D(a);this.resources=I(a);this.root=this.ampdoc.getRootNode();this.aa=null}l=R.prototype;l.report=function(){};l.onBlur=function(){};l.onInput=function(){};l.inputs=function(){return this.form.querySelectorAll("input,select,textarea")};
l.checkInputValidity=function(a){if("TEXTAREA"===a.tagName&&a.hasAttribute("pattern")&&(a.checkValidity()||"Please match the requested format."===a.validationMessage)){var b=a.getAttribute("pattern"),c=new RegExp("^"+b+"$","m"),d=c.test(a.value);a.setCustomValidity(d?"":"Please match the requested format.")}return a.checkValidity()};l.checkFormValidity=function(a){Mb(this,a);return a.checkValidity()};l.reportFormValidity=function(a){Mb(this,a);return a.reportValidity()};
function Mb(a,b){H(b.elements,function(b){"TEXTAREA"==b.tagName&&a.checkInputValidity(b)})}l.fireValidityEventIfNecessary=function(){var a=this.aa;this.aa=this.checkFormValidity(this.form);if(a!==this.aa){var b=Xa(this.form.ownerDocument.defaultView,this.aa?"valid":"invalid",null,{bubbles:!0});this.form.dispatchEvent(b)}};function Nb(){R.apply(this,arguments)}n(Nb,R);Nb.prototype.report=function(){this.reportFormValidity(this.form);this.fireValidityEventIfNecessary()};
function S(a){R.call(this,a);var b="i-amphtml-validation-bubble-"+Lb++;this.S=new Fb(this.ampdoc,b)}n(S,R);S.prototype.report=function(){for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){a[b].focus();this.S.show(a[b],a[b].validationMessage);break}this.fireValidityEventIfNecessary()};S.prototype.onBlur=function(a){"submit"!=a.target.type&&this.S.hide()};
S.prototype.onInput=function(a){a=a.target;this.S.isActiveOn(a)&&(this.checkInputValidity(a)?(a.removeAttribute("aria-invalid"),this.S.hide()):(a.setAttribute("aria-invalid","true"),this.S.show(a,a.validationMessage)))};function T(a){R.call(this,a);this.Na=this.form.id?this.form.id:String(Date.now()+Math.floor(100*Math.random()));this.Ca=0}n(T,R);l=T.prototype;l.reportInput=function(a){var b=Ob(a);b&&this.showValidationFor(a,b)};l.hideAllValidations=function(){for(var a=this.inputs(),b=0;b<a.length;b++)this.hideValidationFor(a[b])};
l.getValidationFor=function(a,b){if(!a.id)return null;var c=b;var d=a.validationMessage;c="TEXTAREA"===a.tagName&&"customError"===c&&"Please match the requested format."===d?"patternMismatch":c;d="__AMP_VALIDATION_"+c;d in a||(a[d]=this.root.querySelector("[visible-when-invalid="+c+"][validation-for="+(a.id+"]")));return a[d]};
l.showValidationFor=function(a,b){var c=this.getValidationFor(a,b);if(c){c.textContent.trim()||(c.textContent=a.validationMessage);a.__AMP_VISIBLE_VALIDATION=c;var d=c.getAttribute("id");d||(d="i-amphtml-aria-desc-"+this.Na+"-"+this.Ca++,c.setAttribute("id",d));a.setAttribute("aria-invalid","true");a.setAttribute("aria-describedby",d);this.resources.mutateElement(c,function(){return c.classList.add("visible")})}};
l.hideValidationFor=function(a){var b=this.getVisibleValidationFor(a);b&&(delete a.__AMP_VISIBLE_VALIDATION,a.removeAttribute("aria-invalid"),a.removeAttribute("aria-describedby"),this.resources.mutateElement(b,function(){return b.classList.remove("visible")}))};l.getVisibleValidationFor=function(a){return a.__AMP_VISIBLE_VALIDATION};l.shouldValidateOnInteraction=function(){throw Error("Not Implemented");};
l.onInteraction=function(a){a=a.target;var b=!!a.checkValidity&&this.shouldValidateOnInteraction(a);this.hideValidationFor(a);b&&!this.checkInputValidity(a)&&this.reportInput(a)};l.onBlur=function(a){this.onInteraction(a)};l.onInput=function(a){this.onInteraction(a)};function Pb(){T.apply(this,arguments)}n(Pb,T);Pb.prototype.report=function(){this.hideAllValidations();for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){this.reportInput(a[b]);a[b].focus();break}this.fireValidityEventIfNecessary()};
Pb.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function U(){T.apply(this,arguments)}n(U,T);U.prototype.report=function(){this.hideAllValidations();for(var a=null,b=this.inputs(),c=0;c<b.length;c++)this.checkInputValidity(b[c])||(a=a||b[c],this.reportInput(b[c]));a&&a.focus();this.fireValidityEventIfNecessary()};U.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function Qb(){T.apply(this,arguments)}n(Qb,T);
Qb.prototype.shouldValidateOnInteraction=function(){return!0};Qb.prototype.onInteraction=function(a){T.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};function Rb(){U.apply(this,arguments)}n(Rb,U);Rb.prototype.shouldValidateOnInteraction=function(){return!0};Rb.prototype.onInteraction=function(a){U.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};
function Sb(a){var b=a.getAttribute("custom-validation-reporting");switch(b){case "as-you-go":return new Qb(a);case "show-all-on-submit":return new U(a);case "interact-and-submit":return new Rb(a);case "show-first-on-submit":return new Pb(a)}a.ownerDocument&&void 0===Jb&&(Jb=!!document.createElement("form").reportValidity);return Jb?new Nb(a):new S(a)}
function Ob(a){var b=["badInput"];for(c in a.validity)b.includes(c)||b.push(c);var c=b.filter(function(b){return!0===a.validity[b]});return c.length?c[0]:null};function Tb(a){var b=a.ownerDocument.defaultView;b.FormProxy||(b.FormProxy=Ub(b));var c=b.FormProxy,d=new c(a);"action"in d||Vb(a,d);a.$p=d}
function Ub(a){function b(a){this.h=a}var c=b.prototype,d=a.Object,e=d.prototype,f=[a.HTMLFormElement,a.EventTarget],g=f.reduce(function(a,b){for(b=b&&b.prototype;b&&b!==e&&!(0<=a.indexOf(b));)a.push(b),b=d.getPrototypeOf(b);return a},[]);g.forEach(function(b){var d={},f;for(f in b){d.w=a.Object.getOwnPropertyDescriptor(b,f);if(d.w&&f.toUpperCase()!=f&&!sa(f,"on")&&!e.hasOwnProperty.call(c,f))if("function"==typeof d.w.value)d.ea=d.w.value,c[f]=function(a){return function(){return a.ea.apply(this.h,
arguments)}}(d);else{var g={};d.w.get&&(g.get=function(a){return function(){return a.w.get.call(this.h)}}(d));d.w.set&&(g.set=function(a){return function(b){return a.w.set.call(this.h,b)}}(d));a.Object.defineProperty(c,f,g)}d={ea:d.ea,w:d.w}}});return b}
function Vb(a,b){var c=a.ownerDocument.defaultView.HTMLFormElement.prototype.cloneNode.call(a,!1),d={},e;for(e in c){d.l=e;if(!(d.l in b||d.l.toUpperCase()==d.l||sa(d.l,"on"))){d.m=Wb[d.l];var f=a[d.l];if(d.m)if(d.m.access==V){d.M=void 0;if(f&&f.nodeType){var g=c=f,h=g.nextSibling;g=g.parentNode;g.removeChild(c);try{d.M=a[d.l]}finally{g.insertBefore(c,h)}}else d.M=f;Object.defineProperty(b,d.l,{get:function(a){return function(){return a.M}}(d)})}else d.m.access==W&&(d.N=d.m.attr||d.l,Object.defineProperty(b,
d.l,{get:function(c){return function(){var d=b.getAttribute(c.N);return null==d&&void 0!==c.m.def?c.m.def:c.m.type==Xb?"true"===d:c.m.type==Yb?null!=d:c.m.type==Zb?(d=d||"",B(a,"url").parse(d).href):d}}(d),set:function(a){return function(c){a.m.type==Yb&&(c=c?"":null);null!=c?b.setAttribute(a.N,c):b.removeAttribute(a.N)}}(d)}));else Object.defineProperty(b,d.l,{get:function(b){return function(){return a[b.l]}}(d),set:function(b){return function(c){a[b.l]=c}}(d)})}d={M:d.M,N:d.N,m:d.m,l:d.l}}}
var W=1,V=2,Zb=1,Xb=2,Yb=3,Wb={acceptCharset:{access:W,attr:"accept-charset"},accessKey:{access:W,attr:"accesskey"},action:{access:W,type:Zb},attributes:{access:V},autocomplete:{access:W,def:"on"},children:{access:V},dataset:{access:V},dir:{access:W},draggable:{access:W,type:Xb,def:!1},elements:{access:V},encoding:{access:V},enctype:{access:W},hidden:{access:W,type:Yb,def:!1},id:{access:W,def:""},lang:{access:W},localName:{access:V},method:{access:W,def:"get"},name:{access:W},noValidate:{access:W,
attr:"novalidate",type:Yb,def:!1},prefix:{access:V},spellcheck:{access:W},style:{access:V},target:{access:W,def:""},title:{access:W},translate:{access:W}};function $b(a,b){var c='form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}textarea[autoexpand]:not(.i-amphtml-textarea-max){overflow:hidden!important}.i-amphtml-textarea-clone{visibility:hidden;position:absolute;top:-9999px;left:-9999px;height:0!important}.i-amphtml-validation-bubble{transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,0.5);max-width:200px;position:absolute;display:block;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:" ";position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{color:red}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/',
d=!1,e="amp-form",f=a.getHeadNode(),g=ac(f,ec(f,c),d||!1,e||null);if(b){var h=a.getRootNode();if(fc(h,g))b(g);else var k=setInterval(function(){fc(h,g)&&(clearInterval(k),b(g))},4)}}
function ac(a,b,c,d){var e=a.__AMP_CSS_SM;e||(e=a.__AMP_CSS_SM=v());var f=!c&&d&&"amp-custom"!=d&&"amp-keyframes"!=d,g=c?"amp-runtime":f?"amp-extension="+d:null;if(g){var h=gc(a,e,g);if(h)return h.textContent!==b&&(h.textContent=b),h}var k=(a.ownerDocument||a).createElement("style");k.textContent=b;var m=null;c?k.setAttribute("amp-runtime",""):f?(k.setAttribute("amp-extension",d||""),m=gc(a,e,"amp-runtime")):(d&&k.setAttribute(d,""),m=a.lastChild);b=m;a.insertBefore(k,b?b.nextSibling:a.firstChild);
g&&(e[g]=k);return k}function gc(a,b,c){return b[c]?b[c]:(a=a.querySelector("style["+c+"]"))?b[c]=a:null}function ec(a,b){return(a=a.__AMP_CSS_TR)?a(b):b}function fc(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++){var d=c[a];if(d.ownerNode==b)return!0}return!1};function hc(a,b,c){Ra(a,"amp-analytics-instrumentation","amp-analytics").then(function(d){d&&d.triggerEventForTarget(a,b,c)})};var ic=["amp-selector"];
function jc(a,b){var c=this;try{Tb(a)}catch(f){t().error("amp-form","form proxy failed to install",f)}a.__AMP_FORM=this;this.ka=b;this.j=a.ownerDocument.defaultView;this.Ma=F(this.j,"timer");this.wa=B(a,"url-replace");this.ja=null;this.h=a;this.Ba=D(this.h);this.A=F(this.j,"templates");this.Sa=F(this.j,"xhr");this.X=B(this.h,"action");this.ua=I(this.h);this.T=G(this.h,"viewer");this.P=new Db(this.T,this.A);this.H=(this.h.getAttribute("method")||"GET").toUpperCase();this.La=this.h.getAttribute("target");
this.L=kc(this,"action-xhr");this.Ra=kc(this,"verify-xhr");this.va=!this.h.hasAttribute("novalidate");this.h.setAttribute("novalidate","");this.va||this.h.setAttribute("amp-novalidate","");this.h.classList.add("i-amphtml-form");this.I="initial";b=this.h.elements;for(var d=0;d<b.length;d++){var e=b[d].name;u("__amp_source_origin"!=e&&"__amp_form_verify"!=e,"Illegal input name, %s found: %s",e,b[d])}this.Z=new xb(this.h,this.j);this.da=Sb(this.h);this.Oa=nb(this.h,function(){return lc(c)});this.X.installActionHandler(this.h,
this.Aa.bind(this));this.la();mc(this);this.pa=this.Ia=this.Qa=null;Ka(E(a),"form-submit-service").then(function(a){c.pa=a})}function kc(a,b){var c=a.h.getAttribute(b);if(c){var d=B(a.h,"url");d.assertHttpsUrl(c,a.h,b);u(!d.isProxyOrigin(c),"form %s should not be on AMP CDN: %s",b,a.h)}return c}l=jc.prototype;
l.requestForFormFetch=function(a,b,c,d){var e="GET"==b||"HEAD"==b;if(e){nc(this);var f=L(this.h);d&&d.forEach(function(a){delete f[a]});c&&ra(f,c);var g=Ba(a,Ca(f))}else{g=a;var h=ub(this.j,this.h);d&&d.forEach(function(a){h.delete(a)});for(var k in c)h.append(k,c[k])}var m={xhrUrl:g,fetchOpt:w({body:h,method:b,credentials:"include",headers:w({Accept:"application/json"})})};return Cb(this.h).then(function(a){a&&(u("POST"==m.fetchOpt.method,"Cannot attach auth token with GET request."),h.append("ampViewerAuthToken",
a));return m})};l.setXhrAction=function(a){this.L=a};l.Aa=function(a){var b=this;if(!a.satisfiesTrust(100))return null;if("submit"==a.method)return oc(this).then(function(){var c=a;return"submitting"!=b.I&&pc(b)?qc(b,c.trust,null):Promise.resolve(null)});"clear"===a.method&&rc(this);return null};function oc(a){if(a.ja)return a.ja;var b=a.h.querySelectorAll(ic.join(",")),c=oa(b).map(function(a){return a.whenBuilt()});return a.ja=sc(a,c,2E3)}
l.la=function(){var a=this;this.Ba.whenNextVisible().then(function(){var b=a.h.querySelector("[autofocus]");if(b)try{b.focus()}catch(c){}});this.h.addEventListener("submit",this.Fa.bind(this),!0);this.h.addEventListener("blur",function(b){tc(b.target);a.da.onBlur(b)},!0);this.P.isSupported()||this.h.addEventListener("change",function(b){a.Oa.onCommit().then(function(c){var d=c.updatedElements,e=c.errors;d.forEach(tc);a.da.onBlur(b);"verifying"===a.I&&(e.length?(X(a,"verify-error"),Y(a,w({verifyErrors:e})).then(function(){uc(a,
"verify-error",e)})):X(a,"initial"))})});this.h.addEventListener("input",function(b){tc(b.target);a.da.onInput(b)})};function mc(a){Ra(a.h,"inputmask","amp-inputmask").then(function(a){a&&a.install()})}function vc(a,b){wc(a,"Form analytics not supported");var c=w({}),d=L(a.h),e;for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(c["formFields["+e+"]"]=d[e].join(","));c.formId=a.h.id;hc(a.h,b,c)}
function rc(a){a.h.reset();X(a,"initial");a.h.classList.remove("user-valid");a.h.classList.remove("user-invalid");var b=a.h.querySelectorAll(".user-valid, .user-invalid");H(b,function(a){a.classList.remove("user-valid");a.classList.remove("user-invalid")});var c=a.h.querySelectorAll(".visible[validation-for]");H(c,function(a){a.classList.remove("visible")});xc(a.h)}
l.Fa=function(a){if("submitting"==this.I||!pc(this))return a.stopImmediatePropagation(),a.preventDefault(),Promise.resolve(null);(this.L||"POST"==this.H)&&a.preventDefault();return qc(this,100,a)};
function qc(a,b,c){try{var d={form:a.h,actionXhrMutator:a.setXhrAction.bind(a)};a.pa.fire(d)}catch(m){t().error("amp-form","Form submit service failed: %s",m)}var e=yc(a),f=a.h.getElementsByClassName("i-amphtml-async-input");a.Z.onSubmitting();if(!a.L&&"GET"==a.H){wc(a,"Non-XHR GETs not supported.");nc(a);if(0===f.length){for(d=0;d<e.length;d++)a.wa.expandInputValueSync(e[d]);var g=!c;zc(a,g);a.Z.onSubmitSuccess();return Promise.resolve()}c&&c.preventDefault()}X(a,"submitting");var h=[],k=[];k.push(Ac(a,
e));H(f,function(b){var c=Bc(a,b);b.classList.contains("i-async-require-action")?h.push(c):k.push(c)});return Promise.all(h).then(function(){return sc(a,k,1E4).then(function(){if(a.L)var c=Cc(a,b);else"POST"==a.H?u(!1,"Only XHR based (via action-xhr attribute) submissions are supported for POST requests. %s",a.h):"GET"==a.H&&zc(a,!0),c=Promise.resolve();return c},function(b){return Dc(a,b)})},function(b){return Dc(a,b)})}
function Dc(a,b){var c={};b&&b.message&&(c.error=b.message);return Ec(a,b,c)}function yc(a){return a.h.querySelectorAll('[type="hidden"][data-amp-replace]')}function lc(a){if("submitting"===a.I)return Promise.resolve();X(a,"verifying");uc(a,"verify",null);return Ac(a,yc(a)).then(function(){return Fc(a)})}function Cc(a,b){a.P.isSupported()?b=Gc(a,b):(Hc(a,b),b=a.$(a.L,a.H).then(function(b){return Ic(a,b)},function(b){return Jc(a,b)}));return b}
function Gc(a,b){var c,d=L(a.h);return Y(a,d).then(function(){return a.X.trigger(a.h,"submit",null,b)}).then(function(){return a.requestForFormFetch(a.L,a.H)}).then(function(b){var d=c=b,e=c.fetchOpt||{};var h=e.method;void 0===h?h="GET":(h=h.toUpperCase(),Bb.includes(h));e.method=h;e.headers=e.headers||w({});d.fetchOpt=e;d=c;h=c.xhrUrl;e=(e=c.fetchOpt)||{};var k=a.j;k=k.origin||y(k.location.href).origin;h=y(h).origin;k==h&&(e.headers=e.headers||{},e.headers["AMP-Same-Origin"]="true");d.fetchOpt=
e;d=c;e=c.xhrUrl;if(!1!==c.fetchOpt.ampCors){h=a.j;k=y(e);k=ma(k.search);u(!("__amp_source_origin"in k),"Source origin is not allowed in %s",e);h=h.location.href;"string"==typeof h&&(h=y(h));k=h;"string"==typeof k&&(k=y(k));if(pa.cdnProxyRegex.test(k.origin)){k=h.pathname.split("/");u(ta[k[1]],"Unknown path prefix in url %s",h.href);var m=k[2],z="s"==m?"https://"+decodeURIComponent(k[3]):"http://"+decodeURIComponent(m);u(0<z.indexOf("."),"Expected a . in origin %s",z);k.splice(1,"s"==m?3:2);k=z+k.join("/");
m=(m=h.search)&&"?"!=m?(m=m.replace(wa,"").replace(xa,"").replace(ya,"").replace(za,"").replace(Aa,"").replace(/^[?&]/,""))?"?"+m:"":"";h=k+m+(h.hash||"")}else h=h.href;h=y(h).origin;h=encodeURIComponent("__amp_source_origin")+"="+encodeURIComponent(h);e=Ba(e,h,void 0)}d.xhrUrl=e;return a.P.ssr(a.h,c,Kc(a))}).then(function(b){return Lc(a,b)},function(b){var c={};b&&b.message&&(c.error=b.message);return Ec(a,b,c)})}
function Kc(a){var b,c=a.h.querySelector("[submit-success]");c&&(b=a.A.maybeFindTemplate(c));var d,e=a.h.querySelector("[submit-error]");e&&(d=a.A.maybeFindTemplate(e));return{successTemplate:b,errorTemplate:d}}function Lc(a,b){var c=b.init;return c&&(c=c.status,300<=c)?Ec(a,c,b):Mc(a,ia(function(){return b}))}function Hc(a,b){vc(a,"amp-form-submit");var c=L(a.h);Y(a,c).then(function(){a.X.trigger(a.h,"submit",null,b)})}
function Ac(a,b){for(var c=[],d=0;d<b.length;d++)c.push(a.wa.expandInputValueAsync(b[d]));return sc(a,c,100)}function Bc(a,b){return b.getImpl().then(function(a){return a.getValue()}).then(function(c){var d=b.getAttribute("name");d=a.h.querySelector("input[name="+String(d).replace(Ma,Na)+"]");if(!d){d=w({name:b.getAttribute("name"),hidden:"true"});var e=a.j.document.createElement("input"),f;for(f in d)e.setAttribute(f,d[f]);d=e}d.setAttribute("value",c);a.h.appendChild(d)})}
function Fc(a){var b=oa(a.h.querySelectorAll("["+"no-verify".replace(Ma,Na)+"]")),c=b.map(function(a){return a.name||a.id}),d={};return a.$(a.Ra,a.H,(d.__amp_form_verify=!0,d),c)}l.$=function(a,b,c,d){var e=this;wc(this,"XHRs should be proxied.");return this.requestForFormFetch(a,b,c,d).then(function(a){return e.Sa.fetch(a.xhrUrl,a.fetchOpt)})};function Ic(a,b){var c=b.json();return Mc(a,c).then(function(){vc(a,"amp-form-submit-success");Nc(a,b)})}
function Mc(a,b){return b.then(function(b){X(a,"submit-success");Y(a,b||{}).then(function(){uc(a,"submit-success",b);a.Z.onSubmitSuccess()})},function(a){r().error("amp-form","Failed to parse response JSON: %s",a)})}function Jc(a,b){return(b&&b.response?b.response.json().catch(function(){return null}):Promise.resolve(null)).then(function(c){vc(a,"amp-form-submit-error");Ec(a,b,c);Nc(a,b.response)})}
function Ec(a,b,c){X(a,"submit-error");r().error("amp-form","Form submission failed: %s",b);return ia(function(){Y(a,c).then(function(){uc(a,"submit-error",c);a.Z.onSubmitError()})})}function zc(a,b){vc(a,"amp-form-submit");b&&a.h.submit();X(a,"initial")}function wc(a,b){var c=a.P.isSupported();u(!1===c,"[amp-form]: viewerRenderTemplate | %s",b)}
function nc(a){var b=a.h.querySelectorAll("input[type=password],input[type=file]");u(0==b.length,"input[type=password] or input[type=file] may only appear in form[method=post]")}function pc(a){void 0===Kb&&(Kb=!!a.j.document.createElement("input").checkValidity);if(Kb){var b=Oc(a.h);if(a.va)return a.da.report(),b}return!0}
function Nc(a,b){wc(a,"Redirects not supported.");if(b&&b.headers){var c=b.headers.get("AMP-Redirect-To");if(c){u("_blank"!=a.La,"Redirecting to target=_blank using AMP-Redirect-To is currently not supported, use target=_top instead. %s",a.h);try{var d=B(a.h,"url");d.assertAbsoluteHttpOrHttpsUrl(c);d.assertHttpsUrl(c,"AMP-Redirect-To","Url")}catch(e){u(!1,"The `AMP-Redirect-To` header value must be an absolute URL starting with https://. Found %s",c)}G(a.h,"navigation").navigateTo(a.j,c,"AMP-Redirect-To")}}}
function uc(a,b,c){c=Xa(a.j,"amp-form."+b,w({response:c}));a.X.trigger(a.h,b,c,100)}function sc(a,b,c){return Promise.race([Promise.all(b),a.Ma.promise(c)])}
function X(a,b){var c=a.I;a.h.classList.remove("amp-form-"+c);a.h.classList.add("amp-form-"+b);var d=a.h.querySelector("["+c+"]");if(d){/^[\w-]+$/.test("i-amphtml-rendered");if(void 0!==Oa)var e=Oa;else{try{var f=d.ownerDocument,g=f.createElement("div"),h=f.createElement("div");g.appendChild(h);e=g.querySelector(":scope div")===h}catch(k){e=!1}e=Oa=e}e?d=d.querySelector("> [i-amphtml-rendered]".replace(/^|,/g,"$&:scope ")):(d.classList.add("i-amphtml-scoped"),e="> [i-amphtml-rendered]".replace(/^|,/g,
"$&.i-amphtml-scoped "),e=d.querySelectorAll(e),d.classList.remove("i-amphtml-scoped"),d=void 0===e[0]?null:e[0]);d&&d.parentElement&&d.parentElement.removeChild(d)}a.I=b}
function Y(a,b){Array.isArray(b)&&(b={},r().warn("amp-form","Unexpected data type: "+b+". Expected non JSON array."));var c=a.h.querySelector("["+a.I+"]"),d=Promise.resolve();if(c){var e="rendered-message-"+a.ka;c.setAttribute("role","alert");c.setAttribute("aria-labeledby",e);c.setAttribute("aria-live","assertive");a.A.hasTemplate(c)?d=a.P.applySsrOrCsrTemplate(c,b).then(function(b){b.id=e;b.setAttribute("i-amphtml-rendered","");return a.ua.mutateElement(c,function(){c.appendChild(b);var d=Xa(a.j,
"amp:dom-update",null,{bubbles:!0});c.dispatchEvent(d)})}):a.ua.mutateElement(c,function(){})}return d}l.Ta=function(){return this.Ia};l.Va=function(){return this.Qa};function Oc(a){var b=a.querySelectorAll("input,select,textarea,fieldset");H(b,function(a){return Z(a)});return Z(a)}
function xc(a){var b=document.createElement("input"),c={},d;for(d in b.validity){c.W=d;var e=a.querySelectorAll("."+String(c.W).replace(Ma,Na));H(e,function(a){return function(b){b.classList.remove(a.W)}}(c));c={W:c.W}}}
function Z(a,b){b=void 0===b?!1:b;if(!a.checkValidity)return!0;var c=!1,d=a.classList.contains("user-valid")?"valid":a.classList.contains("user-invalid")?"invalid":"none",e=a.checkValidity();"valid"!=d&&e?(a.classList.add("user-valid"),a.classList.remove("user-invalid"),c="invalid"==d):"invalid"==d||e||(a.classList.add("user-invalid"),a.classList.remove("user-valid"),c=!0);if(a.validity)for(var f in a.validity)a.classList.toggle(f,a.validity[f]);if(b&&c){f=Qa(a);for(var g=0;g<f.length;g++)Z(f[g]);
a.form&&Z(a.form)}return e}function tc(a){Z(a,!0)}function Pc(a){this.Pa=Qc(a).then(function(){return Rc(a)})}Pc.prototype.whenInitialized=function(){return this.Pa};function Qc(a){var b=new ha;$b(a,b.resolve);return b.promise}function Rc(a){return a.whenReady().then(function(){var b=a.getRootNode();Sc(b.querySelectorAll("form"));hb(a);Tc(b)})}function Sc(a){a&&H(a,function(a,c){var b=a.__AMP_FORM||null;b||new jc(a,"amp-form-"+c)})}
function Tc(a){a.addEventListener("amp:dom-update",function(){Sc(a.querySelectorAll("form"))})}(function(a){a.registerServiceForDoc("form-submit-service",Ab);a.registerServiceForDoc("amp-form",Pc)})(self.AMP);
})});

//# sourceMappingURL=amp-form-0.1.js.map
